SOUNDS = {
    "37 БАЛЛОВ БЛЯТЬ": "AwACAgIAAxkDAAOeaF23sv20nTy1kf7AsAy9zAI93F4AAoRxAAL6_PFKX0-uvaNmdBA2BA",
    "7700K": "AwACAgIAAxkDAAIBx2hzpmvhtkgqPC2JV7jJ3FgPn_BSAAIpcAACgWeYS_MKHtAux9iaNgQ",
    "AVX": "AwACAgIAAxkDAAIBymhzpuGFXSqNz1x_js8RVKRHnJylAAIucAACgWeYSwABWgch5KyKWDYE",
    "BOMB HAS BEEN PLANTED": "AwACAgIAAxkDAAIBS2heUtGwBzJlRxqye0lodLUf3TeiAALXdQAC-vzxSszSv8eWFinGNgQ",
    "ЁБАНЫЙ ПОКАРЁБАНЫЙ": "AwACAgIAAxkDAAIBomhe5PQfQsSBka4GaMT5GZ9oU9S5AAJregAC-vz5SjWMTvJhyNb9NgQ",
    "ЁБАНЫЙ РОТ БЛЯТЬ": "AwACAgIAAxkDAAOfaF23t7b-O7sFw3xzOY2ZwUZJwP0AAuGIAAIY3PBKwLIKc4x_u042BA",
    "ЁБАНЫЙ ТВОЙ РОТ": "AwACAgIAAxkDAAOgaF23vMFp-DWkwa3LQiRP101YZZQAAoZxAAL6_PFKCP0ygrt2NyE2BA",
    "ЁЛЫ ПАЛЫ": "AwACAgIAAxkDAAOhaF23wQZ4gMzvtz54-VbkTwfxdH0AAodxAAL6_PFK0zWlCxuwNU02BA",
    "ААА ЗАЧЕМ": "AwACAgIAAxkDAAOiaF23xrCGwCxJCCugXUiFRITsfjEAAohxAAL6_PFKpTHNPKD7Sks2BA",
    "АДСКИЙ РАЗГОН": "AwACAgIAAxkDAAOjaF23zO8W2j_lPzCjalvWRqi3k_8AAuOIAAIY3PBKL-rGPMkIqB02BA",
    "АЙ БЛЯТЬ": "AwACAgIAAxkDAAICFWiAQd89ZfwZa_SKD4cC6Un-tZ9SAAJQdQACw94ISKwDBvl1ciNWNgQ",
    "АЙ ДА СУКА": "AwACAgIAAxkDAAIBlWheigaOfgsuhBi-u1jSZum3JhVRAAKLeQAC-vzxSpKWUSFaMu2WNgQ",
    "АПЧХИ": "AwACAgIAAxkDAAOkaF230W7eYjTxgddjI_0ORoNLto0AAolxAAL6_PFKCulYU3FK6iA2BA",
    "АХУЕЛ": "AwACAgIAAxkDAAOlaF231uL28U81Rr2mMEl8pRwOG5oAAopxAAL6_PFKUduUgXJkueg2BA",
    "БАБКА СМОТРИ ЛИМОН": "AwACAgIAAxkDAAICSmi3ASlXdvczoOSCV2SXK5gbAjB1AAK4gAACfxa4SYTr8S1GC4axNgQ",
    "БАКЛАН ЕБАНЫЙ БЛЯТЬ": "AwACAgIAAxkDAAOmaF2324JgfaA7r8R0P-0xefv1g3UAAotxAAL6_PFKlPLPpz4zzm02BA",
    "БАКС": "AwACAgIAAxkDAAOnaF234QkfcdzF_nmTQQPDkadlfsMAAuSIAAIY3PBKB_BeNRqve6w2BA",
    "БЛЯ ГОРЯЧУЮ ВОДУ ОТКЛЮЧИЛИ": "AwACAgIAAxkDAAICBmiAQEDwUgNBouhCYRA1VQfPnIKCAAI9dQACw94ISOXDDf5kVN02NgQ",
    "БЛЯТЬ": "AwACAgIAAxkDAAOqaF238EZOzVwqN_aMf5H0DZnV444AAo9xAAL6_PFKBj83TWoLktk2BA",
    "БЛЯТЬ АХАХА": "AwACAgIAAxkDAAOoaF235r512gHhvZKFbbTPqOMD-_AAAo1xAAL6_PFKm_LDjva9nr82BA",
    "БЛЯТЬ БЛЯТЬ БЛЯТЬ": "AwACAgIAAxkDAAOpaF236wulNg0G9eEo5T499b3mnw4AAhx_AAK9q_BK1iu_tMQNTFU2BA",
    "БРЕДИШЬ": "AwACAgIAAxkDAAOraF239fZD6SzAlJ8MGhMJUmJKq9UAApBxAAL6_PFKt_f5jTDX0mM2BA",
    "БУХЫК": "AwACAgIAAxkDAAOsaF23-hQIlrPv0_s38vWy-YD6OdsAApFxAAL6_PFKDH8_ZQPIDqc2BA",
    "БЫЛО АХУЕННО": "AwACAgIAAxkDAAIB-miAQD-Tt_erbjofulgvjaachNYOAAI3dQACw94ISHjbaz9nH5EbNgQ",
    "В МАКДОНАЛЬДС ИДТИ": "AwACAgIAAxkDAAOtaF24AAFzCTsLMrOyz13enRHZDO3_AAKScQAC-vzxShB-ZUQMCGN2NgQ",
    "ВЕЛИКОЛЕПНЫЙ ПЛАН ВОЛТЕР": "AwACAgIAAxkDAAOuaF24BbO2a-5wemIjuCEHcxirPh0AApNxAAL6_PFKQf6bHo0Zr8g2BA",
    "ВЕСЬ ПОЛ ЗАСРАЛ": "AwACAgIAAxkDAAOvaF24CqGpGBIO6-X29LdAOSmVL58AAuWIAAIY3PBKOIcZkNbHAoc2BA",
    "ВИДЕОСОС": "AwACAgIAAxkDAAICOmiZ3ToG65UnLB451s14We_pKWcwAAIbdgACMxrRSClUkeIscXq8NgQ",
    "ВОЗНИКЛИ ВОПРОСЫ": "AwACAgIAAxkDAAOwaF24DxsMXX2R6gXiZNp89bZA3F8AApZxAAL6_PFKb-lvGOTWRW42BA",
    "ВОТ ХЕРНЯ ПРИДУРОК": "AwACAgIAAxkDAAIBRGheUF28t5-evSooKESinh78gKEwAAKsdQAC-vzxShtpkX6ar9uKNgQ",
    "ВСЁ ЕСТЬ": "AwACAgIAAxkDAAOxaF24FBWDH7PU4UI_a_nYVDPOAaYAAphxAAL6_PFKOWqAx-x8N7Y2BA",
    "ВСЁ ПО ЧЕСНОКУ": "AwACAgIAAxkDAAOyaF24GgHbNyDwfQM5PV4Rg6uwR5QAAppxAAL6_PFKIIlldTRifiA2BA",
    "ВСЁ ПРОСТО": "AwACAgIAAxkDAAOzaF24H09-bXuEV3HB6bs1d1KsfBAAAptxAAL6_PFK9CSmG8xfvj42BA",
    "ВСЕГО ХОРОШЕГО": "AwACAgIAAxkDAAIB_GiAQD_onCuC1EmyZjKcJDTu_uRYAAI4dQACw94ISI-1rykQVOrHNgQ",
    "ВСТАВАЙ ЗАЕБАЛ": "AwACAgIAAxkDAAO0aF24JKEMY9KaUit3LLEmW5_Nw1AAAuaIAAIY3PBKwAW5tFC1akM2BA",
    "ВТИРАЕШЬ ДИЧЬ": "AwACAgIAAxkDAAO1aF24KYWB9zRkPnGGLOUZomg7aJAAApxxAAL6_PFKVE0wVvwiAWE2BA",
    "ВЫ ДЕЙСТВИТЕЛЬНО ИДИОТЫ": "AwACAgIAAxkDAAO2aF24LtSr6S1e2iG6I0MjB82LgxgAAp1xAAL6_PFKmJw68uofB-Y2BA",
    "ГАНДОНИО": "AwACAgIAAxkDAAO3aF24NJVev3H8GRP_ASzFn9zh_7oAAuiIAAIY3PBKLEG3ulUXwbw2BA",
    "ГАЧИ ААА": "AwACAgIAAxkDAAO4aF24OROoXTn4XPJCXSUBboqdqccAAp5xAAL6_PFK6pmR2NwVpT02BA",
    "ГОНДОН ХУЕСОС": "AwACAgIAAxkDAAO5aF24PoigGqcl0-ICXh37VyL58aoAAp9xAAL6_PFKZYMz4xO3u902BA",
    "ГУЛЬКИН ЧЛЕН": "AwACAgIAAxkDAAO6aF24QyTOWAn2CRrdTUWyZD5pa1cAAqBxAAL6_PFKBONfb8mfLQY2BA",
    "ДА ЁБАНЫЙ БАРАН": "AwACAgIAAxkDAAO7aF24SEZuh9h35hA6UQHmjJi6cmcAAqJxAAL6_PFKPe8uiZPo-q82BA",
    "ДА ЁБАНЫЙ НАСРАЛ": "AwACAgIAAxkDAAIBp2he5cCZCfbWaKoAARPrpQ-gHySoCQACH3oAAuiY-UonOLr4Au3HlDYE",
    "ДА ДА ДА": "AwACAgIAAxkDAAICKmiRgYc4hWoRGlXY7G3oup2p3a0LAAKEewACM3-QSOpgjPhpUcbyNgQ",
    "ДА ДА НЕ УДИВЛЯЙТЕСЬ": "AwACAgIAAxkDAAO8aF24TS5mBLUg3vT8dl5kCJi7ProAAqNxAAL6_PFKDCsj2aew0ik2BA",
    "ДА КАК ТЫ СМЕЕШЬ": "AwACAgIAAxkDAAICOGiZ3Tpd_lowBh_Q2sh6vp9GWVNPAAIadgACMxrRSLbIsIFyOgxcNgQ",
    "ДА ОБЯЗАТЕЛЬНО": "AwACAgIAAxkDAAIBU2heWPV8E5aa-73UaDeudLD6ApJKAAI_dgAC-vzxStMxiEOOIrnQNgQ",
    "ДА ТЫ ЗАЕБАЛ": "AwACAgIAAxkDAAO9aF24U_OakPpNMmclS75DfEStOkEAAqRxAAL6_PFKHbAzCcg8MXA2BA",
    "ДВА ПАКЕТИКА ТРАВЫ": "AwACAgIAAxkDAAO-aF24WEwnUiiJMwqqfQaKy_70pP8AAqdxAAL6_PFKbxn5vj36fGQ2BA",
    "ДЕГЕНЕРАТ ЕБУЧИЙ": "AwACAgIAAxkDAAO_aF24Xevw4QaRZgtRqVAgIpeQ2iEAAqlxAAL6_PFKar0Z6RWRxzY2BA",
    "ДЕГЕНЕРАТИЛЫ": "AwACAgIAAxkDAAPAaF24Y2jAjjl_E6Nyf0l0M-OzgjcAAqpxAAL6_PFKAgunJbnEsmE2BA",
    "ДЕЛО ЕСТЬ": "AwACAgIAAxkDAAPBaF24aNqesuIj_NVAX_BOhrp8cukAAqtxAAL6_PFKfDabPZBjpIA2BA",
    "ДЕСЯТЬ": "AwACAgIAAxkDAAPCaF24bSMxhj4AAQL50gABsCNhWjxkLgACrXEAAvr88Uo_MeiIffFZYzYE",
    "ДЕТСКИЙ УРОВЕНЬ": "AwACAgIAAxkDAAIBQGheTxZMCOfQFjy0ocrdcTkSe5gUAAKUdQAC-vzxSsHYCK6gvYsFNgQ",
    "ДО СВИДАНИЯ": "AwACAgIAAxkDAAPDaF24chvsqCcvVUODhstQSmCQOOsAAq5xAAL6_PFKsiJyaNMDgfU2BA",
    "ДОБРЫЙ ДЕНЬ": "AwACAgIAAxkDAAPEaF24dxfLRrB7alVDLGx7hPW6AWsAAh9_AAK9q_BKmTOd6hFTYNM2BA",
    "ДОЕБАЛИ УЖЕ": "AwACAgIAAxkDAAPFaF24fAe_q2IpD75TI8mKLz6tlpMAArBxAAL6_PFK66qsPwOrGF42BA",
    "ДРУГАЯ ИСТОРИЯ": "AwACAgIAAxkDAAPGaF24gZYVTwkXnnYC5J2qy1Kex28AArFxAAL6_PFKxkVcnPLylAs2BA",
    "ЕБАЛО НАЧИЩУ": "AwACAgIAAxkDAAPHaF24hz1vevaDrLoQH6QuyrdndWYAArJxAAL6_PFKEJ_emh1IEU42BA",
    "ЕБАНИСЬ ПРОСТО": "AwACAgIAAxkDAAIB32h-QVp4-Yz58PQuCHHbeJ3lb5GUAALcfAACOnTxSzNJ1ym_zJjnNgQ",
    "ЕБАНЬКО": "AwACAgIAAxkDAAPIaF24jAcyNJ5yy44jmC6gVRDoyUkAArNxAAL6_PFKSoaKTOuDrIs2BA",
    "ЕБУЧАЯ БОЧКА": "AwACAgIAAxkDAAPJaF24kfk4i0NglERf84RWi6l-NDQAArRxAAL6_PFKguZ3ljivNKk2BA",
    "ЕБУЧИЙ АЙФОН": "AwACAgIAAxkDAAPKaF24lhDNYXsKOXckg-w0QW11CI0AArVxAAL6_PFKCkKINpoDXus2BA",
    "ЕРЖАН": "AwACAgIAAxkDAAPLaF24mw2maqvggdEqC3G75oYzvNAAArdxAAL6_PFKLG9N_x8O1-k2BA",
    "ЕСЛИ ТЫ ЕСТЬ БОГ": "AwACAgIAAxkDAAICLWiWNCJ6_SOO0wSvGLekIXs4JowyAAJvegACoxWxSLgpQM3SeYsxNgQ",
    "ЕСТЬ КУРИТЬ": "AwACAgIAAxkDAAPMaF24oDuA8M6pKEW04u2GXpAQNngAArhxAAL6_PFKUQvbL4oE2KI2BA",
    "ЕСТЬ ПРОБИТИЕ": "AwACAgIAAxkDAAPNaF24pqafV2fY08dnpSZSmG4Bd7cAArlxAAL6_PFKLdSdV7s3Xko2BA",
    "ЕЩЁ ЛУЧШЕ": "AwACAgIAAxkDAAPOaF24q6LyUHTu5CJ1tIUddAyX-hIAAiJ_AAK9q_BKBT-uPnV9Cak2BA",
    "ЖИРОБАС РАЗГНЕВАЛСЯ": "AwACAgIAAxkDAAIBuWhhI_PzGp9o6E6L43UUx8SZ_WZQAAI9cgAC9w8ISz66NQ4hEEy7NgQ",
    "ЖРЁТ КАК ЕБУЧИЙ БОРОВ": "AwACAgIAAxkDAAIBsGhe5_Lg8FC8fjvrYFi315qOlS6pAAKfegAC-vz5SpKLlh87AAGzvzYE",
    "ЗА ДУШУ БЕРЁТ": "AwACAgIAAxkDAAPPaF24sHrNvvQo0ojd7AN9OrwvB1IAArtxAAL6_PFKTPYdSARw3QI2BA",
    "ЗАЕБАЛИ": "AwACAgIAAxkDAAPRaF24uqxM1pglVwm41ifkkv-s9LwAAumIAAIY3PBKMlrzol65rwU2BA",
    "ЗАЕБАЛИ ШКОЛЬНИКИ": "AwACAgIAAxkDAAPQaF24tYRv-8493LUbdan2Ty1YSUcAAr1xAAL6_PFKB_dDfVojODs2BA",
    "ЗАЕБИСЬ": "AwACAgIAAxkDAAPSaF24wEnv_sbKEayVwEoHY_VsvCsAAr5xAAL6_PFKYNntqGKDr1E2BA",
    "ЗАКРОЙ СУКА ЕБАЛО": "AwACAgIAAxkDAAIBZmhegqIOjbob-9F-PT6mTGU2dRIAA7NzAALomPFK9UK-ROPP8K02BA",
    "ЗАКРОЙ ТЫ ЕБАЛО ГАНДОНИЩЕ": "AwACAgIAAxkDAAIBhWheh5PMoXGF352oobkAAdj7Z4KalAACTXkAAvr88Up-4rhdPwmGRzYE",
    "ЗДАРОВА АГАЛЫЕ": "AwACAgIAAxkDAAPTaF24xeQVaGxCl1N2PouJBR8s-TsAAr9xAAL6_PFKefKPDY5fPJQ2BA",
    "ЗДАРОВА ЗАЕБАЛ": "AwACAgIAAxkDAAPUaF24ypLABLZcMsd7BirlbYBiA0IAAsBxAAL6_PFKfDdMbu_EGWg2BA",
    "ЗДРАВСТВУЙ НЕБО В ОБЛАКАХ": "AwACAgIAAxkDAAPVaF24zwHLIrxiP2KSiQzV5ZvR7hoAAsFxAAL6_PFKCYW0iFKiOik2BA",
    "ИДЕЯ ВАЩЕ ГЕНИАЛЬНАЯ": "AwACAgIAAxkDAAPWaF241OizqM9B03zKm53kAdxWJEUAAsJxAAL6_PFKcNA9-fgBbG82BA",
    "ИЗВИНЯЮСЬ КОНЕЧНО ЗА МАТ": "AwACAgIAAxkDAAPXaF242UpXPOUhcVz4-Ov6puwcAAHvAALDcQAC-vzxSpzpjDBUQtZ4NgQ",
    "ИТАК": "AwACAgIAAxkDAAICH2iAQzEKNiGKN3G0WFDfRcFERtRGAAJcdQACw94ISKyKHU0C_AqJNgQ",
    "КАК СТЕЛИЛ СТАРЫЙ": "AwACAgIAAxkDAAIB_miAQD_WLeFuIy2cb-4EsRoH-p57AAI5dQACw94ISOKKqY-mWiphNgQ",
    "КАК ТЕБЕ ЗВУЧОК": "AwACAgIAAxkDAAIBPWheSKmwWO6Vlcjnb4WAbXDEtPnQAAIndQAC-vzxSlqSTH7S1GkZNgQ",
    "КАЧЕСТВО ЗАПИСИ": "AwACAgIAAxkDAAPYaF243rEpFl6ehLzy3Hg_Aktqz_sAAsRxAAL6_PFKNaPfwa1afg02BA",
    "КВА": "AwACAgIAAxkDAAIB5Wh-S10kOWaKV3AvLDqmr41CYpdQAAJdfQACOnTxS6O4ZT5my3lCNgQ",
    "КОРМИТЬ КОНИКА": "AwACAgIAAxkDAAIBQWheTxvwgc3BmURygU1rJQjdy7ovAAKWdQAC-vzxSnwVfLhQ5e2wNgQ",
    "КОТОРЫЙ ДОЛБАЁБ ВОТ ТАКОЙ": "AwACAgIAAxkDAAIBjWheh9_obLZRKgaeRdELTzTia0cEAAJWeQAC-vzxSlXwIWoAAeik8TYE",
    "КОШАЧИЙ ТРУП": "AwACAgIAAxkDAAIB6miAPalxMCD2D9F8SECTe93H5Sh8AAIedQACw94ISEwOYugUKz25NgQ",
    "КРАСАВА": "AwACAgIAAxkDAAIBY2heW5jWJauxJD6Z96EjHRDQyaffAAJudgAC-vzxSnOU7K6wSxrkNgQ",
    "КРИК УЖАСА": "AwACAgIAAxkDAAIB-WiAQD_UPiVFO_Cg3jMSnYp5SMJAAAI2dQACw94ISA6Bj15HE5bMNgQ",
    "КРЫСА ЁБАНАЯ": "AwACAgIAAxkDAAIBgGheh5MQUCMkOcUpRrjTVfc75DXUAAJLeQAC-vzxSof01bItJ5u-NgQ",
    "КТО НАПИСАЛ СТАЛИН ГУЛАГ": "AwACAgIAAxkDAAPZaF245MKz81IlHqjkPwR3cbXun-kAAsVxAAL6_PFKk1rdDXUi52M2BA",
    "КУПИ ИНТЕЛ": "AwACAgIAAxkDAAIB0GhzqVRvbUbn9AABD1lT1f0ZW6nubwACWHAAAoFnmEtgCo9ta9hb-jYE",
    "ЛЕГЧАЙШЕЕ": "AwACAgIAAxkDAAPaaF246bYnYlVlRpkFe8ml_fCKvNcAAsZxAAL6_PFKIsh_TIEcAAHhNgQ",
    "ЛИМОН": "AwACAgIAAxkDAAICSWi3ASmXsmjPsVhSn-fKo_2H2CgxAAK3gAACfxa4SZBq9KrzZ0NqNgQ",
    "МАЗОХИСТКА ТЫ БЛЯТЬ ДУРА НАХ": "AwACAgIAAxkDAAIBgWheh5Olq-DpvrYNXKAt1Na0OPA9AAJMeQAC-vzxSnSPmzR-0OBUNgQ",
    "МАЙН ФЮРЕР": "AwACAgIAAxkDAAPbaF247piCCLxck8-COHVQo2RXT_4AAsdxAAL6_PFKdqefVousxhU2BA",
    "МАЛОЛЕТКА КОНЧЕННАЯ": "AwACAgIAAxkDAAPcaF2488USPlUe4mxCFUlTEta8sRAAAshxAAL6_PFKWMjd8mRG-V02BA",
    "МАСЛОНАМЁК": "AwACAgIAAxkDAAPdaF24-Q6MXZexpMtqgEcjrzowl-wAAslxAAL6_PFKrzuE5gvrjro2BA",
    "МНЕ ВООБЩЕ ПОХУЙ": "AwACAgIAAxkDAAPeaF24_uXMmHMMy5-QRo3WDNaVGdUAAspxAAL6_PFKKrv8-8j_d1w2BA",
    "МНОГОЛЕТКА": "AwACAgIAAxkDAAPfaF25A7Kiz45UbtqrSNDduhUsEMEAAstxAAL6_PFKmApsj9KRpDs2BA",
    "МОЖНО Я ПРОСТО ХУЙ ПОКАЖУ": "AwACAgIAAxkDAAICAmiAQED30GK3rpHZtIMiElV-EPQzAAI7dQACw94ISJq_fHf7B93HNgQ",
    "МОЛЧИЧА ОЙ БЛЯТЬ": "AwACAgIAAxkDAAIB1mh2mhpEJreN9fRQSPm60Oto59dgAAKQgQACAiOwS_HozCtMlN8JNgQ",
    "НА СВЯЗИ": "AwACAgIAAxkDAAPgaF25CCAtZouGUPAkGtMk_Ml-RrkAAsxxAAL6_PFK44qmaDhS1vc2BA",
    "НАВАЛЮ КУЧУ ГОВНА": "AwACAgIAAxkDAAPhaF25Dd_eYWEtdFprZJiKVUIoe6EAAs1xAAL6_PFKjqjCnuvePMU2BA",
    "НАДО БРАТ РАССЛАБИТЬСЯ": "AwACAgIAAxkDAAIBQmheTyDE5wdHnMJvPt1TKjDCCohBAAKXdQAC-vzxSk0s7zwNKA3ONgQ",
    "НАЙС": "AwACAgIAAxkDAAPiaF25E5oqeHSNpDdzvaXnW73_8SYAAs5xAAL6_PFKAAEvaHP7kZcwNgQ",
    "НАНАНАЙ ЗАЕБИСЬ": "AwACAgIAAxkDAAPjaF25GPNFyPEqAQJ5WbFfB0rtLcQAAs9xAAL6_PFKOj6zAbc8tgM2BA",
    "НАПЕРДЕЛ В СЛОУМОУШЕНЕ": "AwACAgIAAxkDAAIB4mh-Ro0ZEShYRHsM8x8osCwd-KF-AAInfQACOnTxS2euG31KzjgxNgQ",
    "НАУЧИТЕ СУКА": "AwACAgIAAxkDAAIBcmhehiOiIoj9cp0oQ2IY5wQX_eElAAL8cwAC6JjxSkdlRSm0XP8VNgQ",
    "НАХУЙ RYZEN": "AwACAgIAAxkDAAIBzmhzqVOvH5hOpTTrySI8p-vjbq7RAAJXcAACgWeYS2qzPCWfOxSJNgQ",
    "НЕ БРАТИШКА": "AwACAgIAAxkDAAPkaF25HedI0loojcE149yb-D6QIRIAAtJxAAL6_PFKVIQd9y-2faM2BA",
    "НЕ ЗАМАЙ МЕНЯ": "AwACAgIAAxkDAAPlaF25InuIFeCqZh5nIlTKT1azzugAAtNxAAL6_PFKYld5tmTvcLw2BA",
    "НЕ ЗНАЮ 1": "AwACAgIAAxkDAAPmaF25J2agiS-k1iBM6Lavf_QLOH0AAtRxAAL6_PFKz8MrwG2Sw_w2BA",
    "НЕ ЗНАЮ 2": "AwACAgIAAxkDAAPnaF25LNOIWpJ1mAnLgBCaq9jdflQAAtZxAAL6_PFKqWAGLbK5BOU2BA",
    "НЕ ЗНАЮ 3": "AwACAgIAAxkDAAPoaF25Mjg4YM46ah1YherbNjTyIpEAAtdxAAL6_PFKZvHyclH6kR42BA",
    "НЕ ЗНАЮ 4": "AwACAgIAAxkDAAPpaF25N4-5yFQW75H1CdZRsIMQgW8AAthxAAL6_PFKnL0tPHFlXkI2BA",
    "НЕ ПОПАЛ БЛЯТЬ ИЗВИНИ": "AwACAgIAAxkDAAIBl2heigbSWmMFaaCk1xukk1VPbxCAAAKMeQAC-vzxShFY2dV3Iu5tNgQ",
    "НЕ СКУЧАЙ": "AwACAgIAAxkDAAPqaF25PMpFFeywFc46W4ARTpxPG2kAAtlxAAL6_PFKnXAszUisNrI2BA",
    "НЕЖНЕЙШИЙ": "AwACAgIAAxkDAAPraF25QQe8H1QSMMmpaIg4u2kF0r8AAtpxAAL6_PFK3WBc53BPAd82BA",
    "НЕКУЛЬТУРНО": "AwACAgIAAxkDAAPsaF25RndONljp_Ye-VGATK_SycCQAAttxAAL6_PFKSRDlRNzdIQM2BA",
    "НЕРВНО ПОКУРИЛ": "AwACAgIAAxkDAAPtaF25TLl_8pd0bHVvS98xXEBLivUAAtxxAAL6_PFKwPRFTQz_5XE2BA",
    "НИКОГДА НЕ ВЕРНУТЬ": "AwACAgIAAxkDAAICCmiAQEBQyYKX4xCrOJMlyQ-3Qx4KAAI_dQACw94ISD9SZQTkbJtzNgQ",
    "НИХЕРА СЕБЕ": "AwACAgIAAxkDAAPuaF25UYTDdnDwY67OKuFCeUO6yXAAAt1xAAL6_PFK7U-Gs1CjzdE2BA",
    "НОРМАЛЬНО": "AwACAgIAAxkDAAPvaF25VgpWXsO4xGkcaOpJCG58YY0AAt5xAAL6_PFKNJMYkMy7pIw2BA",
    "НОРМАЛЬНУЮ ФОТКУ СКИНУЛ": "AwACAgIAAxkDAAICDWiAQED4a1KpnzLqe08jd9xd0mN6AAJAdQACw94ISBFyWO1tC0_XNgQ",
    "НУ ТЫ ПЛЕСЕНЬ": "AwACAgIAAxkDAAPwaF25WwAB1HAn_k9jEzWkA_Ca_DGZAALfcQAC-vzxSgwsY5BBSKdUNgQ",
    "НЫА": "AwACAgIAAxkDAAPxaF25YK--zVD-cyMOcBWScOMSUuoAAuBxAAL6_PFK4X9rpHN-ZAs2BA",
    "НЫТИКОМ": "AwACAgIAAxkDAAIBpGhe5PSmBu1yKDrkENufOCZ4DjTfAAJsegAC-vz5SjO5AymTSztHNgQ",
    "НЮХНИ ГАЗКУ": "AwACAgIAAxkDAAIBPmheSK6mV1MLTYWBYpZl1mAIAAH68QACKHUAAvr88UpI-ZzxgtDkqjYE",
    "О БЛЯТЬ": "AwACAgIAAxkDAAPyaF25ZZL__LpKdQv75Lym3EHPpRkAAuFxAAL6_PFKgOzbMYGIDA82BA",
    "ОБАНА": "AwACAgIAAxkDAAPzaF25a-TrKsbD3oYYkoDvrdRY3LkAAuJxAAL6_PFKNQ6zR8HQncw2BA",
    "ОБЯЗАН РАЗЪЕБАТЬ": "AwACAgIAAxkDAAP0aF25cANmeajADN_TBok3NHjUgeQAAuNxAAL6_PFKPKBDlDTbj-M2BA",
    "ОГО БЛЯТЬ": "AwACAgIAAxkDAAIB3Gh-QLcaVmgTfKQUfg5jhpxEOTRIAALRfAACOnTxS4du30G4dmKUNgQ",
    "ОДНИ ЦИФРЫ": "AwACAgIAAxkDAAIBQ2heTyaLoZrvy3fjHaVgJntr8T5sAAKYdQAC-vzxSgf_LueA9J13NgQ",
    "ОЙ БЛЯ": "AwACAgIAAxkDAAP1aF25day9VXv37zTQIk8_FzqYDa8AAuRxAAL6_PFKRa9UpYc9XvI2BA",
    "ОЙ БЛЯТЬ ЁБ ТВОЮ МАТЬ": "AwACAgIAAxkDAAIBvGhhOAABMZZ-dVAmIaLSVMD7SDDfZQACFHMAAvcPCEtbhlODKm38LzYE",
    "ОНА РИЛ ТУПАЯ": "AwACAgIAAxkDAAP2aF25ep0Hm3GdozpJzt-jFuDq92wAAu6IAAIY3PBKbN_sqbIdKpY2BA",
    "ООООО": "AwACAgIAAxkDAAP3aF25f0VfbLMNZ8T8OpsXNW19YEkAAuVxAAL6_PFK1_ldRAsjARA2BA",
    "ОПА НИХУЯ": "AwACAgIAAxkDAAP4aF25hJeJtr-25IyNGU7YHJVcnAwAAudxAAL6_PFKLawi1JVDZf82BA",
    "ОПАЗДЫВАЮ": "AwACAgIAAxkDAAP5aF25inKztcFxkSB9NiLouD9Lp4gAAuhxAAL6_PFKQPNbvAQzIiQ2BA",
    "ОСВОБОЖУСЬ": "AwACAgIAAxkDAAP6aF25j9TA7Pbw9sSVnRt2cM0Ca4oAAulxAAL6_PFKTvk5XZkitA42BA",
    "ОТДЫХАЕМ": "AwACAgIAAxkDAAIBUGheWPFyo9r_VYhxlTzJAZ_e7YhYAAI7dgAC-vzxSoehXcfblYT4NgQ",
    "ОТПРАВЛЯЕМ НАХУЙ": "AwACAgIAAxkDAAICFmiAQd9reCe52w4siYagEl4n1cGyAAJRdQACw94ISAukW_ucysOjNgQ",
    "ОХ КАКАЯ ШЛЮШКА": "AwACAgIAAxkDAAP7aF25lIsTs4Q97GDqr-V3neAPFvQAAupxAAL6_PFKXFPrsUjVi3c2BA",
    "ОШИБКА СТОП": "AwACAgIAAxkDAAP8aF25mSlziFB3Pi8S-cbqJxnTNpAAAuxxAAL6_PFK46q9oG2du_Y2BA",
    "ПАЛЬЧИКИ ЛОМАЕТ ШАЛАВА": "AwACAgIAAxkDAAIBf2heh5MSjJut_xcGNEZNFOCGGiE7AAJKeQAC-vzxSlKF5d7g_rGGNgQ",
    "ПЕРЕПИХОН": "AwACAgIAAxkDAAIBnmhe5BPkxn_2MQqpuodr-Uo7aa8jAAJMegAC-vz5SmvV6rEKR-G8NgQ",
    "ПЕТРЕНТО": "AwACAgIAAxkDAAIBxGhzc6O0qtNdro9_kfGXB2ryG9P8AAK_bQACgWeYS9YeGJ5L7IUlNgQ",
    "ПИЗДА": "AwACAgIAAxkDAAP-aF25pMCbsFoZJJK56IM58-0BkBMAAu5xAAL6_PFKSWo8GU6YUIc2BA",
    "ПИЗДА ТЕБЕ": "AwACAgIAAxkDAAP9aF25noP_PYHK66wUfgZUiM-dMLMAAu1xAAL6_PFKBUF2i8xHbZs2BA",
    "ПИЗДАБОЛКА": "AwACAgIAAxkDAAIBlGheigZN8eoAAWVftvtPrBtcQdCxrAACinkAAvr88Ur1ozMOYCIUmTYE",
    "ПИЗДУЙ НА ДАЛЬНИЙ ВОСТОК": "AwACAgIAAxkDAAP_aF25qeydzLIFLemeGXqEhb3YbHMAAu9xAAL6_PFKAz4fi4mClcM2BA",
    "ПИЗДЫ ПОЛУЧИШЬ": "AwACAgIAAxkDAAIBAAFoXbmuPGceN3zYWO9XwzbcQqagTwAC8XEAAvr88Upq18YN5cae4jYE",
    "ПО СИЛАМ СДАТЬ ЕГЭ": "AwACAgIAAxkDAAIBAWhdubPXEx_AafnkMHqZHMjSlP5NAALycQAC-vzxSo1Os1AN_WNvNgQ",
    "ПОВАР": "AwACAgIAAxkDAAIBAmhdubndiTRQxqq-pTLmQCAXsiatAAL0cQAC-vzxSs_e1u6YQUs6NgQ",
    "ПОГНАЛИ НАХУЙ": "AwACAgIAAxkDAAIBA2hdub7mE70AAVt6j6Zzwl-or7OAsgAC8IgAAhjc8EqRCZveEygm9jYE",
    "ПОГРЕМУХУ": "AwACAgIAAxkDAAIBBGhducPKmfvzFko_Rd-ax3yMNTesAAL1cQAC-vzxSjTiPdcSJfGbNgQ",
    "ПОНАБЕРУТ ПО ОБЪЯВЛЕНИЮ": "AwACAgIAAxkDAAIBBWhduckD520zzpGeXCGEAQlO-YHEAAL2cQAC-vzxSjFxEEX87CwhNgQ",
    "ПОПОДРОБНЕЕ": "AwACAgIAAxkDAAIBBmhduc56xdT7kBWvfmAzjcakPXU2AAL3cQAC-vzxShgboZkd9tMRNgQ",
    "ПОЦЫК БЛЯТЬ": "AwACAgIAAxkDAAIBB2hdudO7MQ1W8SCvcDZ7tVgkkyGhAAIxfwACvavwSpAu4z_aRJkNNgQ",
    "ПОШЁЛ В ПИЗДУ ГАНДОНИЩЕ": "AwACAgIAAxkDAAIBj2heh9-29P4jaJf8rN3K3mLHLv52AAJXeQAC-vzxSt6OoA74EWV_NgQ",
    "ПОШЁЛ НАХУЙ": "AwACAgIAAxkDAAIBa2hehYptdG1bBGDkPJAxH8FceAFTAALucwAC6JjxSqypXght5LL8NgQ",
    "ПОШЁЛ НАХУЙ СУКА": "AwACAgIAAxkDAAIBCGhdudjJ-VV6psAHGMjPK5jm4vo9AAL8cQAC-vzxSgb367-clCZNNgQ",
    "ПОШЁЛ СУКА КО МНЕ": "AwACAgIAAxkDAAIBamhehYrzi8OiWufaAAGP3Mdidy97hgACJHkAAvr88UoTTY4OI_q8mTYE",
    "ПРИКИНЬТЕ БЛЯТЬ ГАГА": "AwACAgIAAxkDAAIBCWhdud0xTOpV5KTVv2-Vv-3h8nYGAAL-cQAC-vzxSrI9Ybuv-Xp8NgQ",
    "ПРОСТО ПЕСНЯ ЗАИГРАЛА": "AwACAgIAAxkDAAICCWiAQEBDqU8Rw93ceMo1Bs61yKlUAAI-dQACw94ISOTCB_wGQCIbNgQ",
    "РАЗЪЁБ": "AwACAgIAAxkDAAIBCmhdueMuRWtHUMXHIiXsg3ZEzBX1AAIBcgAC-vzxSiMpPIg8vENlNgQ",
    "РАЗЪЕБАЛ ОКОШКО ПРОДАКШЕН": "AwACAgIAAxkDAAIBC2hdueit-cQv5BNrntWJARIl6upTAAIDcgAC-vzxStsEYxB1MRSeNgQ",
    "РАМАЗАН СМЕХ": "AwACAgIAAxkDAAIBDGhdue2zZyJyPDlh6FYUxLWDPgLxAAIFcgAC-vzxSmF1H7UkmhuRNgQ",
    "РЕКЛАМА КОНТРАЦЕПЦИИ": "AwACAgIAAxkDAAICJ2iRf0YcNhR5rCPsORmM8FhtgnzIAAJ3ewACM3-QSNB770V5oS-fNgQ",
    "САНЯ МИКРО СМЕХ": "AwACAgIAAxkDAAIB2Wh-PzfdZeXDMG9-oAhiGA63jVlAAAKyfAACOnTxS9vPvDci6R3xNgQ",
    "САНЯ УЛЕТЕЛ": "AwACAgIAAxkDAAIBDWhdufKQ1_z1-sMCdlHOcVOgQgKvAAIGcgAC-vzxSuj9hgAB1RX8ljYE",
    "САТИВУ БРАТ": "AwACAgIAAxkDAAIBDmhduffpJ4fvQzJQiIDGSgNm8kkDAAIHcgAC-vzxSojbVHP8CYWqNgQ",
    "СЕЙЧАС ВСЁ ХОРОШО": "AwACAgIAAxkDAAIBm2he4MFN2eP3ass7egMV7INUly4DAAILegAC-vz5SpZpfLLh2zc_NgQ",
    "СЛИТ": "AwACAgIAAxkDAAIBD2hduf38Z0TeAaZ3p4i-6AlZT9GDAAI0bAACLS7xSjYKMZRSs_QJNgQ",
    "СЛУШАЙ МЕНЯ ПОЖАЛУЙСТА": "AwACAgIAAxkDAAICN2iZ3ToYyEvp6sPathJMf3WGbWEvAAIZdgACMxrRSFhqo2cO12rhNgQ",
    "СЛЫШ МУДАК ЁБАНЫЙ": "AwACAgIAAxkDAAICAWiAQD9LTPlj_V2e4BJ1_lJ5aEhtAAI6dQACw94ISH0cIB2oqhI1NgQ",
    "СЛЫШ ТЫ БЛЯТЬ": "AwACAgIAAxkDAAIBP2heSLMFC4HZwr_3vEHVZqp2qTSUAAIpdQAC-vzxSpOVPOsKQA-ZNgQ",
    "СЛЫШЬ ТЫ ЕБАНЬКО ДА ДА ТЫ": "AwACAgIAAxkDAAICP2ibrlksUBCb99_EXqRxfvScByVnAAJ9dwACMxrhSJThSx6FUbmENgQ",
    "СМЕХ ДРИСТУНЯШКИ": "AwACAgIAAxkDAAICMGiWaAbuLsjtLM_Kc3Q-GhPb-Ko3AALSfAACoxWxSNq3cu0Z8qUyNgQ",
    "СМЕХ ЖЕНЁК": "AwACAgIAAxkDAAIBEGhdugIFlGtCpdCRBy1W654lXcVRAAIJcgAC-vzxSvzJWGjzBtgbNgQ",
    "СМЕХ МОЛЧИЧИ": "AwACAgIAAxkDAAIB02h2mccL2osFCJmM2Mr2UZp66G8eAAKJgQACAiOwSyLicXjwIzE9NgQ",
    "СМЕХ ШКИЛЫ": "AwACAgIAAxkDAAIBEWhdugfSGCZB7aVvHRltGAY-hMrEAAILcgAC-vzxSuB14BmFswFjNgQ",
    "СРАНЫЙ ТЫ АЛХИМИК": "AwACAgIAAxkDAAIBEmhdugwwW8OIwB9ik3dqcscLJyyiAAIMcgAC-vzxSsdBXneAUxnUNgQ",
    "ССАЛ В ЭТИ БАНКИ": "AwACAgIAAxkDAAIBE2hduhF_i8KZtTBmFAmU8RWXh22WAAINcgAC-vzxSlLy_dvrzMvmNgQ",
    "СУКА АХАХ": "AwACAgIAAxkDAAICRWizS6fYTgkNl4wO934QHpPUXTjBAAJphQACBregSdO9apfVXr0eNgQ",
    "СУКА ТЫ КОНЧЕННАЯ": "AwACAgIAAxkDAAIBFGhduhZHY9ZLq7YLKwNhB2KxoMUcAAIOcgAC-vzxSpTQmt2txAfVNgQ",
    "СУКАААА": "AwACAgIAAxkDAAIBFWhduhwryArOq5XSSdt7CYs2i6YAAzZsAAItLvFK0br9IoVS3KY2BA",
    "СУПЕР СМЕХ": "AwACAgIAAxkDAAIBFmhduiGioWdyc78NKCBLhBnCBOx5AAIQcgAC-vzxSo3cZs59WlDFNgQ",
    "ТВАЮ МАТЬ": "AwACAgIAAxkDAAIBF2hduiZTqUlbgStfZKIgt1XV2997AAIRcgAC-vzxSnr--6fLmoD8NgQ",
    "ТЕБЕ В ПОМОЙКАХ ШАРИТЬ": "AwACAgIAAxkDAAIBGGhduivxVt4orSRyHlcQ7kLsHIPXAAIUcgAC-vzxSkUDMFirAaF3NgQ",
    "ТЕЛЕГРАММОМ БОЛЬШЕ НЕ ПОЛЬЗУЮСЬ": "AwACAgIAAxkDAAIBGWhdujA0kk0yVcZ50DAjhAp5WTv8AAIVcgAC-vzxSkNDhUgfgxWyNgQ",
    "ТЕСТОВАЯ СРАНЬ": "AwACAgIAAxkDAAICGmiAQd8ZoV79XccZBj26ntbApGUyAAJTdQACw94ISPDKQk24nFffNgQ",
    "ТОВАРИЩИ РЕБЯТА": "AwACAgIAAxkDAAIBGmhdujbY_ejs8PKtSJU_i78ngkBDAAIWcgAC-vzxSh85Wx0VQhI6NgQ",
    "ТРИ ПОДПИСЧИКА": "AwACAgIAAxkDAAICUWjGtjnUGxKOMKRdw3faWOv1lOvbAAIydAAC2qM5ShUQ8KxuAAG0QjYE",
    "ТУ НАМБЕР НАЙН": "AwACAgIAAxkDAAIBG2hdujuGQzqaSqMEY2ls5PkCkJEOAAIYcgAC-vzxSr0D3a3s3fRCNgQ",
    "ТЫ ЕБАНУШКА": "AwACAgIAAxkDAAIBHGhdukA2hX1qlOE6QL3DZgjVeQ-8AAIZcgAC-vzxSiVT30RvnyY4NgQ",
    "ТЫ КАК ЭТУ ХУЙНЮ ПРИДУМАЛ": "AwACAgIAAxkDAAIB6WiAPamvDC6QIERsCc-86POlIkTzAAIddQACw94ISFfxKxC2ITvvNgQ",
    "ТЫ ЛОХ ТЫ ХУЙ": "AwACAgIAAxkDAAIBHWhdukWONMfr-sbhap38IBlbHlX0AAIacgAC-vzxSrhiR3otFpmeNgQ",
    "ТЫ ТОЛСТАЯ МАНДА": "AwACAgIAAxkDAAIBHmhdukqE1g0lY6w97Ay980gh3WRpAAIbcgAC-vzxSn7BjtENNJ3_NgQ",
    "ТЫ ЧЁ ОБОСРАЛСЯ": "AwACAgIAAxkDAAIBH2hdulCfVscOgG8Lj2jsvUEFWtUtAAIccgAC-vzxSi_YlzXINfP0NgQ",
    "УЁБОК": "AwACAgIAAxkDAAICJGiRfymfo54F-Q3dZqPcsa5ruD4KAAJ0ewACM3-QSKzOqYjxtqq4NgQ",
    "УБЬЮ НАХУЙ": "AwACAgIAAxkDAAIBIGhdulX7-Z-5Y27BLwuB1yQoDqDuAAIecgAC-vzxSt-MvRDXtFSoNgQ",
    "УБЬЮ НАХУЙ ЩАС БЛЯТЬ": "AwACAgIAAxkDAAIBd2hehjNffFiNEfv0UI-VfWW8l1aFAAIyeQAC-vzxSvJvnMHfOE7VNgQ",
    "УПАЛ": "AwACAgIAAxkDAAIBIWhdulogScATAsDbOiWkr-32jv-iAAIfcgAC-vzxSvakD5oCUP4lNgQ",
    "УЧИТЬСЯ ГОДАМИ": "AwACAgIAAxkDAAIBImhdul_6wdvFpgmhAseFhlO4QOXYAAL9iAACGNzwSr6ZFkqJEUNzNgQ",
    "ХЕР ЕГО ЗНАЕТ": "AwACAgIAAxkDAAIBI2hdumT9Zo_gfpLwutJ41eJAP5tNAAIhcgAC-vzxShU842LKljPeNgQ",
    "ХЕРНЯ КАКАЯ-ТО": "AwACAgIAAxkDAAIBJGhdumkiIL5mFloR0329WJlhQ0UbAAIicgAC-vzxSnGPZQqmaEJ5NgQ",
    "ХУЁК С КОРОБОК": "AwACAgIAAxkDAAIBVmheWPkCYF9D3wRNByE2qD6pzHZoAAJBdgAC-vzxSjowpzYvbp4gNgQ",
    "ХУЛИ ВЫЁБЫВАЕШЬСЯ": "AwACAgIAAxkDAAIBJWhdum7hu4G_mc2n0sfRafcmUApYAAIkcgAC-vzxSp3vYryjNjS_NgQ",
    "ХУЛИ ТЫ СДЕЛАЛ": "AwACAgIAAxkDAAIBJmhdunRVyXLX5ru-ruxjKcFTUsUmAAI0fwACvavwSrOg-fx5Jt_tNgQ",
    "ХУЯК": "AwACAgIAAxkDAAIBJ2hdunmmJR1L3A7uXaiHIwGWOFzaAAImcgAC-vzxSrE7s1hmM_TyNgQ",
    "ЧЁ ЕЩЁ НА КАРМАНЕ": "AwACAgIAAxkDAAIBKGhdun565ONXsQnRfuGDNPrjz4fFAAIncgAC-vzxSuXr1BxJ3Du6NgQ",
    "ЧЁ ЗА ЕБАНЬКО БЛЯТЬ": "AwACAgIAAxkDAAICVGjGtqiGAAGNbg8elxBdo0LmX2YrNwACOXQAAtqjOUrc6MKIHlxdmTYE",
    "ЧЁ ЗА ХУЙНЯ": "AwACAgIAAxkDAAIBKWhduoNmydJJE3jQY-N7T6qNjq55AAIocgAC-vzxSnNdET4Cc3BfNgQ",
    "ЧЁ МНЕ ДЕЛАТЬ С ТОБОЙ": "AwACAgIAAxkDAAICBGiAQEAy73e1HS4AAbvh08_Ryqxf2gACPHUAAsPeCEj0wf38VIGT_TYE",
    "ЧЁ НАДО СУКА": "AwACAgIAAxkDAAIBKmhduogw7Wn5n85PHF5OMno2V5K7AAIpcgAC-vzxSj1EMT4VF5zsNgQ",
    "ЧЁ СКАЗАТЬ ХОТЕЛ": "AwACAgIAAxkDAAIBK2hduo26eNKyqr5FEi5eLW2LNpWrAAIqcgAC-vzxSlepQQJaZpOvNgQ",
    "ЧЁ ТАМ КУРИТ": "AwACAgIAAxkDAAIBLGhdupM3nPer8r5Ec29fWZnfRvWAAAIrcgAC-vzxSrqfmXR_F8ycNgQ",
    "ЧЁТКО": "AwACAgIAAxkDAAIBLWhdupjxnRs_3_lR7sV4xwLXagWWAAIscgAC-vzxSpBQT_6WnkGxNgQ",
    "ЧИВО БЛЯТЬ": "AwACAgIAAxkDAAIBLmhdup3HzzeQzH1LX5sAAaGLzehUygACNX8AAr2r8EoLOIve6LsXUzYE",
    "ЧИКИ БРИКИ": "AwACAgIAAxkDAAIBL2hduqIdnchVN7uMpwRevAV0dY11AAItcgAC-vzxStUrcwlfTHZGNgQ",
    "ЧИСТИ РАЗ РАЗ РАЗ": "AwACAgIAAxkDAAIBMGhduqe3CdnVZZl7aGbozK7uf_45AAIucgAC-vzxSvZTQxqGklWQNgQ",
    "ЧТО БЛЯТЬ": "AwACAgIAAxkDAAIBMWhduq3JbOFvHskLCuUZnOlJ9zH0AAIwcgAC-vzxSkLQXIdf991aNgQ",
    "ЧТО ЭТО ТАКОЕ": "AwACAgIAAxkDAAIBMmhdurK3V8rc6Wv04tY1EXfXTOm-AAIxcgAC-vzxSmBZ00YgVSnyNgQ",
    "ЧУТЬ НЕ УМЕР": "AwACAgIAAxkDAAIBM2hdurdsW0KTQZSagkAaIRpTLPJfAAIBiQACGNzwShXvFENF7JfcNgQ",
    "ШКОЛЬНИКИ СО ШКОЛЫ": "AwACAgIAAxkDAAIBXWheWZriy95Ps3VTscVTZn6CmAi1AAJRdgAC-vzxSqsAAUZG7-m5EjYE",
    "ШКОЛЬНИКИ СО ШКОЛЫ ВЕРНУЛИСЬ": "AwACAgIAAxkDAAIBNGhdurwFZnrA7Mj_tk3pC7yJRDXYAAIzcgAC-vzxSowMBGXSy1uMNgQ",
    "ШМЕЛЬ": "AwACAgIAAxkDAAIBs2he66OBYhRWlG2AA1-hwZcl4g8YAAKwdwACLS75Srtf1HNj-spsNgQ",
    "ЭЙ БОМЖАРА": "AwACAgIAAxkDAAIBNWhdusEg6R6Kxw1uBoag09Jpuh27AAI0cgAC-vzxSn_pKaJox9lwNgQ",
    "ЭМОЦИИ В СТОРОНУ": "AwACAgIAAxkDAAIBNmhdusZf3e_fv8Pa74mIdO2SysWWAAI3cgAC-vzxSvro61kh9byZNgQ",
    "ЭТО БИЗНЕС": "AwACAgIAAxkDAAIBN2hduszO8y1pxsAcMXbRPiE3ecYKAAI4cgAC-vzxSnbMkRfsW3WeNgQ",
    "ЭТО ОНА БЛЯТЬ ВОТ СИДИТ": "AwACAgIAAxkDAAIBh2heh5O1WT6wUUagM_YTRmR2gllCAAJOeQAC-vzxSsJFOtsZ86k9NgQ",
    "ЭТО ПИЗДЕЦ": "AwACAgIAAxkDAAIBOGhdutFYfqcj0lWykhGtTu8oetg_AAI6cgAC-vzxSuxztuCw9baiNgQ",
    "Я АЖ ЗАОРАЛ": "AwACAgIAAxkDAAIBYGheWjFysIovAVW7grwCjQ7Qmf68AAJZdgAC-vzxSmuwlDNSuxkYNgQ",
    "Я Б ЗА ТАКОЕ ВЪЕБАЛ": "AwACAgIAAxkDAAIBg2heh5OO8-_4NQpcltMa91F7SpITAAK3cwACLS7xSsTE7Qe1B4yiNgQ",
    "Я В ЯРОСТИ ОТ ТЕБЯ": "AwACAgIAAxkDAAICNmiZ3ToHe84GH2fE0Q0u2C2UvI3BAAIYdgACMxrRSLWaD-ZIzKRBNgQ",
    "Я ДУМАЛ ТРЫНДЕЦ": "AwACAgIAAxkDAAIBtmhg_ucHmHfncmLePcxMxEr5DdVRAAIKdwACCq0JSzN6IP7uhGP8NgQ",
    "Я ЕБАЛ": "AwACAgIAAxkDAAICIWiAQzErT-eAFzJsgGJzP2dZLZUtAAJddQACw94ISLkCVvtc7Ud2NgQ",
    "Я ЕГО ВЫЧИСЛЮ": "AwACAgIAAxkDAAIBOWhdutafBMUtVRHvc8i90xxT-xVxAAI7cgAC-vzxSi47zo-yQMndNgQ",
    "Я Ж ПОШУТИЛ": "AwACAgIAAxkDAAIBOmhdutyobvrXIJqPaBzorNQCApAGAAI8cgAC-vzxSlQCZ8oYQCK2NgQ",
    "Я ЗАЛЁЖИВАЮСЬ": "AwACAgIAAxkDAAICD2iAQEDDLUkbGtVvtzN7dZfg5bHuAAIvdQAC6yEBSJTJC7pHYxKyNgQ",
    "Я ОДИН ЗДЕСЬ": "AwACAgIAAxkDAAIBO2hduuEzPmzl9fhS6Hx676CzfD_AAAI-cgAC-vzxSsMY7dPmQcxyNgQ",
    "Я СКАЗАЛ ИДИ НА ХУЙ": "AwACAgIAAxkDAAIBc2hehiNOSmH5Z65TY_cOcLgX57bNAAIveQAC-vzxSq7kt6McEGuoNgQ",
    "Я СНИМАЮ БЕЗ ВАЙФАЯ БЛЯТЬ": "AwACAgIAAxkDAAICGWiAQd_ToiDlfPT9iuY7s_fsuPZ4AAJSdQACw94ISIwu6-ywMrB3NgQ",
    "Я ТЕБЯ УМОЛЯЮ": "AwACAgIAAxkDAAIBPGhduuaFj5JGyIGG09cm7jfIaeLzAAI_cgAC-vzxSngPmRfwNU3MNgQ",
}
